---
- hosts: all
  become: yes
  tasks:
    - name: Create Hardware file
      get_url:
        url: http://ansible.example.com/hwreport.empty
        dest: /root/hwreport.txt

    - name: Copy content
      copy:
        content: |
          Inventory Hostname={{ ansible_facts['hostname'] }}
          Total Mamory in MB={{ ansible_facts['memtotal_mb'] }}
          BIOS version={{ ansible_facts['bios_version'] }}
          Size of disk device vda={{ ansible_facts['devices']['vda']['size'] | default ('NONE') }}
          Size of disk device vdb={{ ansible_facts['devices']['vdb']['size'] | default ('NONE') }}
        dest: /root/hwreport.txt
         
