---
- hosts: dev
  become: yes
  tasks:
    - name: webdev group must exist
      group:
        name: webdev
        state: present
 
    - name: Create a directory
      file:
        path: /webdev
        group: webdev
        mode: 7752
        setype: httpd_sys_content_t
        state: directory

    - name: create a link
      file:
        dest: /webdev
        src: /var/www/html/webdev
        state: link


    - name: add text
      copy:
        content: Development
        dest: /webdev/index.html
        setype: httpd_sys_content_t

    - name: add firewall rule
      firewalld:
        service: http
        state: enabled
        immediate: yes
        permanent: yes
