name: Ansible Lint
on:
  workflow_dispatch:
    
jobs:
  linting:
    name: Lint Ansible files
    runs-on: ubuntu-latest


    steps:
    - name: checout sources
      uses: actions/checkout@v2
    - name: Ansible Lint
      uses: ansible-community/ansible-lint-action@v6.3.0
      with:
        agrs: "-c .ansible-lint"  